name: Build and deploy dotnet core app to Azure Function App - test01pips

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'          # folder that has host.json, workflows/, connections.json
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Optional) You can remove setup-dotnet entirely for pure Logic Apps, but leaving it is harmless
      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Package the Logic App (no dotnet build)
      - name: Create deployment package
        shell: bash
        run: |
          cd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          mkdir -p out
          # include the standard Logic Apps Standard artifacts
          zip -r ../package.zip host.json connections.json workflows/ 2>/dev/null || true
          # include local.settings.json only if you really need it (usually NO for cloud deployment)
          cd -

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FC844E6562CE4183B4A3B32B5BB5A661 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DE7FB96AC4774AFFB3403FD7A2BD83FC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3939B82B4984448786680AC252A1676E }}

      - name: Deploy to Azure Functions (Logic Apps Standard)
        uses: Azure/functions-action@v1
        with:
          app-name: test01pips
          slot-name: Production
          package: package.zip
